# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
#export CATALINA_HOME=/tmp			#wrong
#export JAVA_HOME=/tmp              #wrong
